### ISSUE TITLE
Underscore in private functions pattern

### ISSUE THREAD

**Issue by pdgonzalez872** [rrrene/credo-proposals#50]
Hi @rrrene !

I searched the issues and didn't find about this, if this was discussed before, please point me to it.

I've seen the `defp _something()` pattern before in a few projects. In fact, it is in the Programming Elixir book (not that it matters since it is not part of the official docs), but arguably one of the first things folks interested in Elixir are likely to read.

The pattern and an argument for the pattern:
```
data
|> function_a()
|> _function_b() # you can tell it is private. Not an import or another public function.
```

We don't see the pattern in Elixir core. We do see a lot of `defp do_something` though.

I'd be nice if Credo or the Formater would nudge folks on this matter. I love when de facto tools settle these personal preference concerns with defaults.

I'm not sure this should be a check, but thought we would like shed some light on it. 

What are your thoughts?

Thanks for all of the work on Credo.

Paulo

**Comment by rrrene** [comment]
Hi Paulo,

thx for taking the time to write this up.

As far as I can tell (and I am happy to stand corrected on this), the situtation is as follows:

- a leading underscore for variables and parameters indicates that they are not used
- sometimes functions are prefixed and suffixed by double underscores (see `__using__` or the `__info__` function included in every module)

I am not sure that I have ever seen the pattern you describe (could you point to the section in "Programming Elixir" where it is used?).

I am unsure whether or not it would be a good idea to indicate the visibility of something via its name (although I do know this was/is a thing in JavaScript) and from your example it seems like you want to differentiate between public funs, imported funs and private funs, which is not solved by marking just one of the three kinds of funs (and have you thought about public funs that are not part of the supported API, but public for technical reasons?).

I am not saying this is an invalid approach, I am just cautious whether or not it is widely applicable.

I do think that Credo should enable programmers in the programming that they do, which is why there are custom checks and plugins to make Credo your own (and I am working on better documentation for both).

So, maybe you can elaborate: What do you think would be the benefit of the proposed idiom? Can you give a more specific scenario where this helped you?

**Comment by rrrene** [comment]
@pdgonzalez872 I stumbled on this and thought of our discussion: https://hexdocs.pm/elixir/1.10.1/naming-conventions.html#underscore-_foo

**Comment by pdgonzalez872** [comment]
> indicate the visibility of something via its name

This well worded and exactly what I think the strongest use case (at least in
my opinion) was for using this "style"/pattern.

> Programming Elixir

It is used throughout the book, but the first usage I could see was here:

![Screenshot from 2020-03-01 11-06-23](https://user-images.githubusercontent.com/8906358/75630036-d5f00180-5bac-11ea-8941-cc411cd5e4de.png)


> proposed idiom

At the moment I'm not for or against this, just wanted to know an opinion and
have an open discussion about it. Sorry to use you as a sounding board, but I've come to look to your opinions on style as the source of truth for Elixir :)

> when it helped you

Interestingly enough, it did help me in some code I wrote and had to come back
after a couple of months. Due to this "visual shortcut" I was
able to understand the code better at a first glance. Other than that, I'm
neutral on this topic and always favor consistency: if you have the pattern in
the project, follow it, if you don't no need to introduce it. If you ask around and learn the pattern is just a "because it was here", maybe it is time to remove the pattern then.

> moving forward

Now that I think about it (and write this down), I don't think I Credo should do anything with it. I just saw some unnecessary discussion about this in a project and wanted to discuss with the source of truth :)

As usual, thanks for the nice chat and your time! I always learn something from these discussions. :heart:
