### ISSUE TITLE
[proposal] gradual introduction of a check

### ISSUE THREAD

**Issue by InoMurko** [rrrene/credo-proposals#55]
Lets say I have an old repository that has a couple of issues that I could sort with gradual introduction of credo strictness (additional checks). For example, I would like to introduce `Credo.Check.Readability.SinglePipe`. Currently, there's around 370 occurrences of this pattern, but we would like to get rid of it incrementally. I would like to keep the standard checks, but have the ability to run specific checks, for example:
`mix credo Credo.Check.Readability.SinglePipe | grep -c "Use a function call when a pipeline is only one function long" ` and prevent new occurrences from being added to the repo. Afaik, this isn't possible at the moment?

**Comment by rrrene** [comment]
@InoMurko This sounds like a case for `--checks` (which is aliased as `--only`). It takes a comma-delimited list of patterns that are matched against the check models name.

```bash
mix credo --only Credo.Check.Readability.SinglePipe
```

Might be what you are looking for. WDYT?

**Comment by InoMurko** [comment]
Ohhhh! Yes that's it! Should this be included in `mix credo --help` or `mix credo suggest --help` perhaps? I was looking for this and ... didn't find it!

**Comment by InoMurko** [comment]
Now that I've tried this @rrrene I think this isn't it. `mix credo --only Credo.Check.Readability.SinglePipe` would only work if `SinglePipe` is already enabled in the credo config.

If it's set to false:
```
{Credo.Check.Readability.SinglePipe, false},
```
```
mix credo --only Credo.Check.Readability.SinglePipe
Checking 546 source files (this might take a while) ...
A pattern was given to filter checks, but it did not match any: ["Credo.Check.Readability.SinglePipe"]
```
Edit:
But this can all be accomplished with `--ignore-checks` and `--only` indeed!

**Comment by pdgonzalez872** [comment]
I've seen a mechanism used before for "gradual fixes" although it wasn't for Credo, but I'm sure there is some type of mechanism here for it as well. It has to do with creating a file (that either holds the good files or the bad files) and then running the check based on either including (if good files) or excluding (if bad files).

The idea is that the file is used as a temporary shim, that is not to be maintained forever, but can be used to stop the bleeding and eventually have the checks all pass. Eventually you delete the file and make all files included for the checks.

Here is an example where this was used to keep track of files that were not formatted:
https://github.com/FarmBot/farmbot_os/pull/547#issuecomment-389916732

Here is the file: https://github.com/pdgonzalez872/farmbot_os/blob/credo_formatter_02/formatted_files

Then when the task wants filenames as inputs, you could do a `File.read/1` to create them accordingly.

I don't remember exactly how this turned out. I think things were fixed quickly and then life was good after that.

Does that make sense @InoMurko @rrrene? Thought I'd mention an alternative

**Comment by InoMurko** [comment]
Interesting approach! I would def. consider this, if our current take won't work long term.
We simply make two credo passes in Circle:
```
mix credo --ignore-checks Credo.Check.Readability.SinglePipe
```
And after that:
```
_counter=$(mix credo --only Credo.Check.Readability.SinglePipe | grep -c "Use a function call when a pipeline is only one function long")
echo "Current Credo.Check.Readability.SinglePipe occurrences:"
echo $_counter
if [ $_counter -gt 367 ]; then
  echo "Have you been naughty or nice? Find out if Santa knows."
  exit 1
fi
```
Like for now, you could get around this by simply remove a pipe somewhere and introduce it elsewhere. 
Every now and then, the 367 number would need to be updated. Not perfect, but...

**Comment by pdgonzalez872** [comment]
Nice! This is also a nice approach.

With either approach though, you want to aggressively remove either solution :) haha

Thanks for sharing yours!
