### ISSUE TITLE
Feature: add SARIF output format

### ISSUE THREAD

**Issue by hauleth** [rrrene/credo-proposals#58]
### What do you want Credo to do?

Provide formatter that will output data in [SARIF](http://sarifweb.azurewebsites.net) format. This will allow [direct GitHub support](https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/uploading-a-sarif-file-to-github) via `Security` tab.

**Comment by raw-cs** [comment]
This request is several years old.  Since Github Advanced Security supports any SCATs that are able to export to SARIF this would be extremely useful to bubble up security issues directly in PRs.

Has there been discussion on exporting to SARIF?

**Comment by michaelcfanning** [comment]
This does look like a useful feature. Microsoft/the SARIF technical committee would be glad to help with or simply contribute this change. Here's an issue tracking the [FlawFinder](https://github.com/david-a-wheeler/flawfinder/issues/33) SARIF support we authored that provides some additional context (and which also has pointers to the [Brakeman](https://github.com/presidentbeef/brakeman/pull/1500) and [Spotbugs](https://github.com/spotbugs/spotbugs/pull/1185) support we authored.

We also contributed SARIF export for [Sobelow](https://github.com/nccgroup/sobelow/issues/77). The absence of `Credo` support has recently come up as a critical gap for the Elixir language, would love to help close it.

**Comment by rrrene** [comment]
I just a pushed a [branch with a stub for SARIF support](https://github.com/rrrene/credo/tree/sarif-output-stub).

When using Credo from the `sarif-output-stub` branch, one can use `mix credo --format sarif` which in turn uses `Credo.CLI.Output.Formatter.SARIF` to format the output.

At this moment, that module is just a clone of the JSON one, but anyone interested in contributing SARIF support can branch off the mentioned branch and be on their way :+1:

**Comment by michaelcfanning** [comment]
Excellent! @shaopeng-gh, this support looks very valuable for several reasons. Let's work on a contribution.

@rrrene has really set the table for us with the output-stub branch. If you examine/search on other formatters, e.g., the [Oneline](https://github.com/rrrene/credo/blob/63ab97164b039f573076bc5793a1eb45c27c71e3/lib/credo/cli/output/formatter/oneline.ex#L4) support, that may help fill out any missing details.

I'll follow up with you offline to help with SARIF'isms or anything else. Naively, `check` appears to translate to SARIF rule/reporting descriptor data, `message` to SARIF result messages, `filename` to physical locations, `priority` will need to be mapped to SARIF failure levels. I believe that the `ignore` priority will need to translate into a SARIF suppression.

My suggestions here:
* `low` -> SARIF `note`
* `normal` -> SARIF `warning`
* `high` or `higher` SARIF `error`

In order to distinguish between `high` and `higher` consumers will need to consult the SARIF [`rank`](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317663) property. It looks as though we can emit a `rank` value for everything in Credo, see [priority.ex](https://github.com/rrrene/credo/blob/63ab97164b039f573076bc5793a1eb45c27c71e3/lib/credo/priority.ex), because numeric priorities drive the Credo priority buckets. The range for `low` is -10 through -1, which isn't valid for SARIF (1.0 to 100.0 inclusive) so we'll need some simple remapping (e.g., just bump the Credo priority by 11, so that the lowest `low` priority of -10 remaps to the lower SARIF rank of 1.0. As you work on this, maybe sanity check the Credo code base to see if we could propose a Credo change to synchronize this data (this could be a non-starter for Credo for back-compat reasons, though).

If we convert `ignore` to a literal suppression, we don't have the ability to communicate what the severity level *would* have been if it weren't ignored. So for this case, just omit the failure level (which will default to `warning`). This is another question we could pose @rrrene, would it be helpful to retain some notion of perceived severity for a finding that's ignored. Just a moving forward question, nothing to block on for the immediate work. By the way - Credo supports `warning` as an explicit tag on rules, this is actually a reference to a specific class of findings. I think this (and other checker tags) need to surface as SARIF tags. They are static on the rule, so the rule metadata is the right place to decorate (not each result).

Per the general [JSON formatter](https://github.com/rrrene/credo/blob/master/lib/credo/cli/output/formatter/json.ex), looks like our SARIF JSON should be pretty-printed. This formatter has a notion of `scope` which in SARIF terms looks like a logical location: please include that data if you can. A very advanced log emit would express the complete scope change as discrete elements: if the JSON simply expresses the innermost node, stick with that for now. Be sure to consider populating the full name of the logical location and separating the innermost node's name.

The JSON formatter also makes it clear we can provide `line_no`, `column` and `column_end`, these likely map to SARIF `startLine`, `startColumn` and `endColumn`. Be sure to confirm whether Credo's details are 1-indexed, as they are in SARIF. Also, please confirm that every Credo finding is restricted to a single line, I assume this may be true, otherwise `column_end` would be an ambiguous value (without an explicit end line).

As usual, there is a conversation around rule metadata. It appears that [`category`](https://github.com/rrrene/credo/blob/master/lib/credo/cli/command/categories/categories_command.ex) is a conceptual grouping, such as `readability` and `design`. However, looks like these are a bit field (i.e., tags), and that an individual rule can have multiple. That means this data shouldn't be burned into the rule id. 

Looking at the [`check`](https://github.com/rrrene/credo/blob/63ab97164b039f573076bc5793a1eb45c27c71e3/lib/credo/check.ex#L148), I see evidence of formatted messages, which means we could in theory build reporting descriptors in the `rules` table (assuming we can grab relevant data at the extensibility point that drives output). Looking at an [example check](https://github.com/rrrene/credo/blob/63ab97164b039f573076bc5793a1eb45c27c71e3/lib/credo/check/readability/multi_alias.ex#L4) though it appears the rule emits a fully-realized string. That fully realized string may actually have line details expressed in it (which we generally do not support in SARIF). You may need to parse this off. Don't struggle too much to parameterize the finding if it looks difficult. Credo's output looks nice and very SARIF friendly: fully realized sentences with periods at the end of them. :)

Getting back to `rules` metadata, check `explanations` seem to comprise information that could be persisted as explanatory text in the SARIF `rules` table. I couldn't easily figure out what `issue.trigger` refers to, suggest you get a nice example of Credo's JSON output and see what you can find.

Hope some of the above is helpful, be careful accepting specific advice or thinking this analysis is the end of the matter. :) This was my first look at the code-base.

**Comment by shaopeng-gh** [comment]
Sounds great, I will take a look,

**Comment by shaopeng-gh** [comment]
@rrrene 
1. when mapping `priority` to SARIF, we plan to translate:
low -> SARIF `note`
normal -> SARIF `warning`
high or higher  -> SARIF `error`
Question, `ignore` priority, is it for the scan engine to skip things, and will not exist in the result json and SARIF file? If `ignore` priority results will be written to json result (sarif result should be same), we should translate it to SARIF.
2. do a check only has one `category` only? or a check can belong to more than one? 
In the current json output it looks like only one.
``` json
"issues": [
    {
      "category": "design",
      "check": "Credo.Check.Design.TagTODO",
      "column": null,
      "column_end": null,
      "filename": "lib/credo/check/consistency/space_around_operators.ex",
      "line_no": 31,
      "message": "Found a TODO tag in a comment: # TODO: add *ignored* operators, so you can add \"|\" and still write",
      "priority": 2,
      "scope": "Credo.Check.Consistency.SpaceAroundOperators",
      "trigger": "# TODO: add *ignored* operators, so you can add \"|\" and still write"
    }
]
```

**Comment by rrrene** [comment]
@shaopeng-gh The ignore priority is just an internal value (as you suspected). An issue can only have a single category. 👍

**Comment by EasyRhinoMSFT** [comment]
Hello @rrrene 
We'd like to make a change request to add a new property which can be used for the SARIF `rule.id` property.

Currently, we get a human-readable value such as `Credo.Code.Name.full(issue.check)`. The descriptive string is a good fit for `rule.name` but lacks the opacity of a stable rule identifier. Providing both an ID and a name allows you to, for example, change the taxonomy of the rule names without breaking existing logs.

Currently:

    "tool": {
        "driver": {
          "informationUri": "http://credo-ci.org/",
          "name": "Credo",
          "rules": [
            {
              "id": "Credo.Check.Design.TagFIXME",
              ...
            },

With a stable, opaque identifier:

    "tool": {
        "driver": {
          "informationUri": "http://credo-ci.org/",
          "name": "Credo",
          "rules": [
            {
              "id": "CREDO4321",
              "name": "Credo.Check.Design.TagFIXME",
              ...
            },

Here is a link to the spec section that explains property:
[https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317643](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317643)

Thanks for considering this request @rrrene, please let me know if I can be of further assistance.

**Comment by rrrene** [comment]
@EasyRhinoMSFT How would this work with custom checks created by Credo's users which do not have such an identifier? Would this opaque identifier be mandatory?

**Comment by michaelcfanning** [comment]
This is a good question, handling custom checks is tricky. Probably would make most sense to reserve some range for Credo itself and to provide a recommendation for plug in authors for creating their own. There's not a lot of risk entailed by id duplication, except for some amount of customer confusion and the possibility of over-suppression (if you have an in-source or side-car suppression mechanism that uses the opaque ids).

For easiest back-compatibility, you could allocate your own Credo opaque ids and use them, then fall back to populating this data value with the more human-readable forms available today.

One other small thing, in some domains the prefix refers to the language. So at MS, CS1001 is a C# rule id, and C6001 is an opaque id for a C/C++ check. You consider that as well, as opposed to using your tool name. Sometimes, it is valuable to define ids that capture the intent/specification of an analysis and multiple engines may implement it. And so a language-specific id makes sense.

**Comment by rrrene** [comment]
> For easiest back-compatibility, you could allocate your own Credo opaque ids and use them, then fall back to populating this data value with the more human-readable forms available today.

Sounds good to me.

> One other small thing, in some domains the prefix refers to the language. So at MS, CS1001 is a C# rule id, and C6001 is an opaque id for a C/C++ check. You consider that as well, as opposed to using your tool name. Sometimes, it is valuable to define ids that capture the intent/specification of an analysis and multiple engines may implement it. And so a language-specific id makes sense.

I can push an update to `master` introducing IDs. Based on the input from this thread, I would use these IDs:

- `EX1001` - `Credo.Check.Consistency.ExceptionNames`
- `EX1002` - `Credo.Check.Consistency.LineEndings`
- `EX1003` - `Credo.Check.Consistency.MultiAliasImportRequireUse`
- `EX1004` - `Credo.Check.Consistency.ParameterPatternMatching`
- `EX1005` - `Credo.Check.Consistency.SpaceAroundOperators`
- `EX1006` - `Credo.Check.Consistency.SpaceInParentheses`
- `EX1007` - `Credo.Check.Consistency.TabsOrSpaces`
- `EX1008` - `Credo.Check.Consistency.UnusedVariableNames`

- `EX2001` - `Credo.Check.Design.AliasUsage`
- `EX2002` - `Credo.Check.Design.DuplicatedCode`
- `EX2003` - `Credo.Check.Design.SkipTestWithoutComment`
- `EX2004` - `Credo.Check.Design.TagFIXME`
- `EX2005` - `Credo.Check.Design.TagTODO`

- `EX3001` - `Credo.Check.Readability.AliasAs`
- `EX3002` - `Credo.Check.Readability.AliasOrder`
- `EX3003` - `Credo.Check.Readability.BlockPipe`
- `EX3004` - `Credo.Check.Readability.FunctionNames`
- `EX3005` - `Credo.Check.Readability.ImplTrue`
- `EX3006` - `Credo.Check.Readability.LargeNumbers`
- `EX3007` - `Credo.Check.Readability.MaxLineLength`
- `EX3008` - `Credo.Check.Readability.ModuleAttributeNames`
- `EX3009` - `Credo.Check.Readability.ModuleDoc`
- `EX3010` - `Credo.Check.Readability.ModuleNames`
- `EX3011` - `Credo.Check.Readability.MultiAlias`
- `EX3012` - `Credo.Check.Readability.NestedFunctionCalls`
- `EX3013` - `Credo.Check.Readability.ParenthesesInCondition`
- `EX3014` - `Credo.Check.Readability.ParenthesesOnZeroArityDefs`
- `EX3015` - `Credo.Check.Readability.PipeIntoAnonymousFunctions`
- `EX3016` - `Credo.Check.Readability.PredicateFunctionNames`
- `EX3017` - `Credo.Check.Readability.PreferImplicitTry`
- `EX3018` - `Credo.Check.Readability.PreferUnquotedAtoms`
- `EX3019` - `Credo.Check.Readability.RedundantBlankLines`
- `EX3020` - `Credo.Check.Readability.Semicolons`
- `EX3021` - `Credo.Check.Readability.SeparateAliasRequire`
- `EX3022` - `Credo.Check.Readability.SingleFunctionToBlockPipe`
- `EX3023` - `Credo.Check.Readability.SinglePipe`
- `EX3024` - `Credo.Check.Readability.SpaceAfterCommas`
- `EX3025` - `Credo.Check.Readability.Specs`
- `EX3026` - `Credo.Check.Readability.StrictModuleLayout`
- `EX3027` - `Credo.Check.Readability.StringSigils`
- `EX3028` - `Credo.Check.Readability.TrailingBlankLine`
- `EX3029` - `Credo.Check.Readability.TrailingWhiteSpace`
- `EX3030` - `Credo.Check.Readability.UnnecessaryAliasExpansion`
- `EX3031` - `Credo.Check.Readability.VariableNames`
- `EX3032` - `Credo.Check.Readability.WithCustomTaggedTuple`
- `EX3033` - `Credo.Check.Readability.WithSingleClause`

- `EX4001` - `Credo.Check.Refactor.ABCSize`
- `EX4002` - `Credo.Check.Refactor.AppendSingleItem`
- `EX4003` - `Credo.Check.Refactor.Apply`
- `EX4004` - `Credo.Check.Refactor.CaseTrivialMatches`
- `EX4005` - `Credo.Check.Refactor.CondStatements`
- `EX4006` - `Credo.Check.Refactor.CyclomaticComplexity`
- `EX4007` - `Credo.Check.Refactor.DoubleBooleanNegation`
- `EX4008` - `Credo.Check.Refactor.EnumHelpers`
- `EX4009` - `Credo.Check.Refactor.FilterFilter`
- `EX4010` - `Credo.Check.Refactor.FilterReject`
- `EX4011` - `Credo.Check.Refactor.FunctionArity`
- `EX4012` - `Credo.Check.Refactor.IoPuts`
- `EX4013` - `Credo.Check.Refactor.LongQuoteBlocks`
- `EX4014` - `Credo.Check.Refactor.MapInto`
- `EX4015` - `Credo.Check.Refactor.MapJoin`
- `EX4016` - `Credo.Check.Refactor.MapMap`
- `EX4017` - `Credo.Check.Refactor.MatchInCondition`
- `EX4018` - `Credo.Check.Refactor.ModuleDependencies`
- `EX4019` - `Credo.Check.Refactor.NegatedConditionsInUnless`
- `EX4020` - `Credo.Check.Refactor.NegatedConditionsWithElse`
- `EX4021` - `Credo.Check.Refactor.NegatedIsNil`
- `EX4022` - `Credo.Check.Refactor.Nesting`
- `EX4023` - `Credo.Check.Refactor.PerceivedComplexity`
- `EX4024` - `Credo.Check.Refactor.PipeChainStart`
- `EX4025` - `Credo.Check.Refactor.RedundantWithClauseResult`
- `EX4026` - `Credo.Check.Refactor.RejectFilter`
- `EX4027` - `Credo.Check.Refactor.RejectReject`
- `EX4028` - `Credo.Check.Refactor.UnlessWithElse`
- `EX4029` - `Credo.Check.Refactor.VariableRebinding`
- `EX4030` - `Credo.Check.Refactor.WithClauses`

- `EX5001` - `Credo.Check.Warning.ApplicationConfigInModuleAttribute`
- `EX5002` - `Credo.Check.Warning.BoolOperationOnSameValues`
- `EX5003` - `Credo.Check.Warning.ExpensiveEmptyEnumCheck`
- `EX5004` - `Credo.Check.Warning.ForbiddenModule`
- `EX5005` - `Credo.Check.Warning.IExPry`
- `EX5006` - `Credo.Check.Warning.IoInspect`
- `EX5007` - `Credo.Check.Warning.LazyLogging`
- `EX5008` - `Credo.Check.Warning.LeakyEnvironment`
- `EX5009` - `Credo.Check.Warning.MapGetUnsafePass`
- `EX5010` - `Credo.Check.Warning.MixEnv`
- `EX5011` - `Credo.Check.Warning.OperationOnSameValues`
- `EX5012` - `Credo.Check.Warning.OperationWithConstantResult`
- `EX5013` - `Credo.Check.Warning.RaiseInsideRescue`
- `EX5014` - `Credo.Check.Warning.SpecWithStruct`
- `EX5015` - `Credo.Check.Warning.UnsafeExec`
- `EX5016` - `Credo.Check.Warning.UnsafeToAtom`
- `EX5017` - `Credo.Check.Warning.UnusedEnumOperation`
- `EX5018` - `Credo.Check.Warning.UnusedFileOperation`
- `EX5019` - `Credo.Check.Warning.UnusedFunctionReturnHelper`
- `EX5020` - `Credo.Check.Warning.UnusedKeywordOperation`
- `EX5021` - `Credo.Check.Warning.UnusedListOperation`
- `EX5022` - `Credo.Check.Warning.UnusedOperation`
- `EX5023` - `Credo.Check.Warning.UnusedPathOperation`
- `EX5024` - `Credo.Check.Warning.UnusedRegexOperation`
- `EX5025` - `Credo.Check.Warning.UnusedStringOperation`
- `EX5026` - `Credo.Check.Warning.UnusedTupleOperation`
- `EX5027` - `Credo.Check.Warning.WrongTestFileExtension`


Would these IDs work for the purposes discussed above?

**Comment by shaopeng-gh** [comment]
Would these IDs work for the purposes discussed above? --- Look good from my side and I like how you use different range for each category.

Would this opaque identifier be mandatory --- this would be an important one we need to settle @rrrene @michaelcfanning 
fyi what I plan to do based on your decision:

currently SARIF rule name is from calling this method: `Credo.Code.Name.full(issue.check)`
after your implementation you can let me know the method to get the opaque id for the checks, just an example so I can write the code below `Credo.Code.Name.id(issue.check)`

### if we design this as **not** mandatory:

```elixir
first check if there is opaque id for the current check, there wont be any for all the custom checks unless they add it,
(let me know if by checking Credo.Code.Name.id(issue.check) == nil)

if there is opaque id for this check, I will:
    "id" => Credo.Code.Name.id(issue.check),
    "name" => Credo.Code.Name.full(issue.check),
if there is no, I will use the human readable check name as SARIF rule id:
    "id" => Credo.Code.Name.full(issue.check),
(because when name is the same as id, we don't need to duplicate id into name.)
```

### if we design this as mandatory:

```elixir
always:
    "id" => Credo.Code.Name.id(issue.check),
    "name" => Credo.Code.Name.full(issue.check),
```

**Comment by rrrene** [comment]
@shaopeng-gh I just pushed an update to `master` which allows you to call `issue.check.id` to get the ID of the check :+1:

**Comment by shaopeng-gh** [comment]
Cool thanks, above question I describe I will use it differently , mandatory v.s. not mandatory.
Let me know @rrrene 

if not mandatory, let me know how I check if there is opaque id for a check, do I check if `issue.check.id == nil`.
if mandatory, let me know if existing custom checks will be broken.

**Comment by rrrene** [comment]
Oops, wasn't clear enough: `issue.check.id` always returns a value - opaque ID if provided, check name otherwise (as fallback).

I added the opaque IDs for all standard checks yesterday on `master`. 👍

**Comment by rrrene** [comment]
I've merged the PR and cleaned up the code a bit.

@shaopeng-gh Could you check the current `master` and confirm that my changes have not altered critical parts of the formatting?

**Comment by shaopeng-gh** [comment]
Looks good to me, thanks! I have tried using the latest master.

**Comment by rrrene** [comment]
FYI: SARIF support is part of the release candidate: `v1.7.0-rc.1` :+1:
