### ISSUE TITLE
New Check: comparing unsorted lists in test assertion - potentially flaky

### ISSUE THREAD

**Issue by ghost** [rrrene/credo-proposals#90]
### What do you want Credo to do?

Use some heuristic for flagging assertions that are likely to be flaky when dealing with lists. For example, it could raise a check failure when comparing two lists directly using an assertion, and redirect user to use an assertion function which sorts its arguments.

**Comment by rrrene** [comment]
I like this idea in principle as I encountered this problem in the past. 

This be harder to implement than some other ideas, simply because (a) Credo does not have any notion that a variable is a list and (b) the false positive rate on this check has to minimal, therefore, we would need an extensive test suite.

**Comment by ghost** [comment]
can possibly focus on when LHS or RHS is a list constant value

**Comment by rrrene** [comment]
Comparing LHD and RHD is a great way to showcase my point!

Example:

```elixir
  test "the truth" do
    assert MyApp.some_function(:some_argument, 42) == [:correct, 3]
  end
```

How could we possibly deduce if this is prone to flakiness?

**Comment by ghost** [comment]
That makes sense. I'm okay with closing if you don't see any way to proceed to a real feature.
